import { z } from "zod"
/* -------------------------------------------------------------------------- */
/* Persisted theme color input                                                */
/* -------------------------------------------------------------------------- */

import { oklchColorSchema, semanticColorOverridesSchema } from "../colors/model"
import { appearancePreferenceSchema } from "@repo/features-preferences"

export const themeColorSchema = z.object({
  base: oklchColorSchema,
})

export type ThemeColor = z.infer<typeof themeColorSchema>

/* -------------------------------------------------------------------------- */
/* Brand colors                                                               */
/* -------------------------------------------------------------------------- */

export const themeColorsSchema = z.object({
  primary: oklchColorSchema,
  accent: oklchColorSchema,

  /**
   * Optional explicit neutral anchor.
   * If omitted, the compiler can derive a neutral family from the theme.
   */
  neutral: oklchColorSchema.optional(),

  /**
   * Optional overrides.
   * Missing semantic colors are generated by the theme compiler.
   */
  semantic: semanticColorOverridesSchema,
})

export type ThemeColors = z.infer<typeof themeColorsSchema>

export const themeFormSchema = z.object({
  appearance: appearancePreferenceSchema,
  primary: oklchColorSchema,
  accent: oklchColorSchema.optional(),
})

export type ThemeFormValues = z.infer<typeof themeFormSchema>
