import { z } from "zod"

import { oklchColorSchema, semanticColorOverridesSchema } from "../color/model"

/* -------------------------------------------------------------------------- */
/* Persisted theme color input                                                */
/* -------------------------------------------------------------------------- */

export const themeColorSchema = z.object({
  base: oklchColorSchema,
})

export type ThemeColor = z.infer<typeof themeColorSchema>

/* -------------------------------------------------------------------------- */
/* Brand colors                                                               */
/* -------------------------------------------------------------------------- */

export const themeColorsSchema = z.object({
  primary: oklchColorSchema,
  accent: oklchColorSchema,

  /**
   * Optional explicit neutral anchor.
   * If omitted, the compiler can derive a neutral family from the theme.
   */
  neutral: oklchColorSchema.optional(),

  /**
   * Optional overrides.
   * Missing semantic colors are generated by the theme compiler.
   */
  semantic: semanticColorOverridesSchema,
})

export type ThemeColors = z.infer<typeof themeColorsSchema>

/* -------------------------------------------------------------------------- */
/* Scoped overrides                                                           */
/* -------------------------------------------------------------------------- */

/** Per-scope theme overrides, persisted by the runtime theme-scope store. */
export interface ThemeOverrides {
  primaryColor?: string
}
